### ISSUE TITLE
Makefile depends on GNU core utilities ('make install' fails on OSX)

### ISSUE THREAD

**Issue by blmorris** [micropython/micropython-lib#10]
The reason appears to be that the GNU and BSD versions of 'find' require different options:

```
bryans-computer:micropython-lib bryan$ make install
find: illegal option -- m
find: illegal option -- a
find: illegal option -- e
find: illegal option -- p
find: illegal option -- t
find: illegal option -- h
find: 1: No such file or directory
```

I haven't yet figured out how to modify the command to work on OSX, will continue to look into it.
Reference for BSD (OSX) find (the man page on OSX is basically the same):
https://www.freebsd.org/cgi/man.cgi?query=find(1)&sektion=
Reference for GNU find:
http://linux.die.net/man/1/find

**Comment by jonnor** [comment]
No motion over the last 9 years. I am pretty sure that Mac OSX builds have worked for many years already.
