### ISSUE TITLE
Unconnected MQTT publish fails silently

### ISSUE THREAD

**Issue by mkarliner** [micropython/micropython-lib#112]
If I connect up an MQTT client and publish (sucessfully), then stop the broker, subsequent publishes fail without error. I'm not sure if this is the desired functionality or not. In fact, its a bit opaque to me how robust achieves  its reconnection functionality.

connected with mihome, channel 6
dhcp client start...
ip:192.168.10.185,mask:255.255.255.0,gw:192.168.10.1

> > > from simple import MQTTClient
> > > c = MQTTClient("adcdd", "192.168.10.195") # Broker not running
> > > c.connect()
> > > 0
> > > c.publish("foo", "Hello MQTT")
> > > ..# Stop broker
> > > c.publish("foo", "Hello MQTT")
> > > # No exception....

**Comment by pfalcon** [comment]
> In fact, its a bit opaque to me how robust achieves its reconnection functionality.

It doesn't have to be like that - code is at every MicroPython user's fingertips and simple to understand: https://github.com/micropython/micropython-lib/blob/master/umqtt.robust/umqtt/robust.py#L29

I'll look into the main topic of this issue when time permits.

**Comment by mkarliner** [comment]
Sorry, me being unclear. Looking at the code, I wonder how robust would reconnect in a situation other than a publish failure?

**Comment by pfalcon** [comment]
Subscription requires running event loop (wait_msg() function). It's also protected in a similar fashion to publish(): https://github.com/micropython/micropython-lib/blob/master/umqtt.robust/umqtt/robust.py#L37

**Comment by mkarliner** [comment]
Thanks for the explanation, obvious now you say.

**Comment by jonnor** [comment]
The question seems to have been resolved. Proposing to close.
