### ISSUE TITLE
os.listdir() causes _Comparison between bytes and str_ warnings

### ISSUE THREAD

**Issue by dxxb** [micropython/micropython-lib#114]
This is caused by ```if fname not in (b".", b"..", ".", ".."):``` at https://github.com/micropython/micropython-lib/blob/master/os/os/__init__.py#L137

AFAICS uos.ilistdir() accepts a string or byte argument but always returns an entry's name as string. os.ilistdir() replacement instead always returns an entry's name as bytes. Would it be acceptable to make os.ilistdir() always return an entry's name as string and simplify os.listdir()? It would also make the warning go away.

**Comment by pfalcon** [comment]
This was fixed.
