### ISSUE TITLE
Versioning scheme for modules from CPython stdlib

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython-lib#12]
For modules imported from CPython stdlib, I saw far just set version as 1.0, and then added/incremented micro version if any tweaks were later required.

But I guess, it would be more informative to set version to CPython's version from which module was imported, and then probably add revision suffix for any changes, e.g. "3.3.3-1". Hyphen in revision suffix of course assumed PyPI is ok with it (needs testing).

Comments welcome.

**Comment by jonnor** [comment]
No motion for over 9 years. Proposing to close this issue.
