### ISSUE TITLE
Error during connect

### ISSUE THREAD

**Issue by rlust** [micropython/micropython-lib#125]
I get the following error when calling the client.connect() command

File "simple.py", line 56, in connect
OSError: [Errno 103] ECONNABORTED

I have tried this on several ESP8266s
Any ideas?

**Comment by dpgeorge** [comment]
Did you start the MQTT server?  Did you pass the correct address of the server to the MQTTClient() constructor?  If you provide more information about your set-up then it'll be easier to diagnose.

**Comment by pfalcon** [comment]
Hopefully comment above was enough to diagnose the issue. Closing, feel free to reopen with additional information pointing that the problem is on micropython-lib side.
