### ISSUE TITLE
uasyncio missing EventLoop method?

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython-lib#127]
Why is there no EventLoop method
``call_later_ms(self, delay, callback, *args)``
analogous to the existing
``call_later(self, delay, callback, *args)``?

**Comment by pfalcon** [comment]
https://github.com/micropython/micropython-lib/commit/02a6625a0076368014e351303810ecaa9765b266

**Comment by peterhinch** [comment]
OK.
