### ISSUE TITLE
umqtt.simple subscription without callback?

### ISSUE THREAD

**Issue by askvictor** [micropython/micropython-lib#130]
It would be useful to have a non-blocking message check method that doesn't require a callback - it checks if there is a message, and returns the data if there is data, otherwise returns None. If there are multiple messages, it might return a list of them, or perhaps a subsequent call returns the next message. Callbacks can introduce timing issues, and for simple use-cases this would make things easier.

**Comment by pfalcon** [comment]
> and for simple use-cases this would make things easier.

That's how it was initially conceived, but the need to handle QoS>0 and stakeholders argument for supporting more than just "simple use-cases" called for that design. You're welcome to trace the umqtt design discussion if you're interested.

The interface of umqtt.simple is now fixed, sorry. But from your own description it's clear how to implement what you want - have callback add messages to a list, have a getter method which pops a message from the list or waits for it. Don't hesitate to subclass MQTTClient - it's intended to be.
