### ISSUE TITLE
README installation instructions need a fix

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython-lib#132]
The instructions as written are out of date: pip-micropython has been replaced by upip which requires micropython to run. The installation instructions could be more newbie-friendly.

There should be a pointer to the docs on how to build micropython and an instruction to ensure that micropython is on the path. The first line of the example should then read:

```python
micropython -m upip install micropython-copy
```

It might also be worth putting in a pointer as to how to transfer the library from ~/.micropython onto the target - ideally in a cross-platform manner.

I'm happy to submit a PR for this - but I'm not in a position to test under Windows or OSX. Perhaps someone else is better placed. Please advise if you want me to proceed on a Linux basis.

**Comment by pfalcon** [comment]
Thanks, I wondered what's the source of people still trying to use pip-micropython, and it was right  before my nose. I've updated README to the current state of affairs.

I don't think that micropython-lib's README is the right place to discuss all things upip, after all, upip can be used to install other packages outside micropython-lib. The best place is apparently upip's own README, which yet needs to be written and that may can perhaps be thought out in the meantime.
