### ISSUE TITLE
List of functions/functionality which will not be included

### ISSUE THREAD

**Issue by Snigelson** [micropython/micropython-lib#137]
Is there a comprehensive list of what functions and functionality which will never be included in micropython-lib? It would be nice knowing if you should ask for what you are missing, or if you should just try and work around it.

The list could also include alternatives and workarounds.

**Comment by pfalcon** [comment]
> or if you should just try and work around it.

Well, for MicroPython itself is that's what is suggested, per https://github.com/micropython/micropython/wiki/ContributorGuidelines#django-criteria .

However, as micropython-lib is modular, there's no same pressure to NOT include something in it. The aim would be as compatible with CPython's stdlib as makes sense. Of course, there're fine issues, like a module which can be used on low-heap bare-metal systems vs the unix port - for small systems, keeping module bare is preferrable (but we have a concept of "u" modules to at least partially avoid deadlock here).

And of course, preparing, and then maintaining a list would require bunch of time, which instead can be used to actually implement missing features.

So, the general rule of thumb is: micropython-lib contains something which people needed and implemented. More things will be added as they become needed up to being actually implemented (and implemented well enough to be merged).
