### ISSUE TITLE
cpython-uasyncio: broken by gzip 4k conversion

### ISSUE THREAD

**Issue by ThunderEX** [micropython/micropython-lib#150]
commit dfe4dee62a662793709dbc7c0531580ba5a2371b and 65fb3707ba4d35068971f996aa9664cf9ae7be78 break cpython-uasyncio by introducing such line in setup.py:
```
import optimize_upip
```
and thus, cpython report ImportError, cpython-uasyncio 0.2.1 package on PyPI don't include setup.py, causing this package broken.

**Comment by pfalcon** [comment]
Ok, so the idea how to fix this is to introduce new `srctype` in metadata.txt for such packages, for example:

~~~
srctype = cpython-wrapper
~~~

Comments on a specific value to use are welcome.

**Comment by dpgeorge** [comment]
> Comments on a specific value to use are welcome.

Or `cpython-adaptor`

**Comment by pfalcon** [comment]
Well, "cpython-adaptor" sounds too narrow/specialized IMHO.

**Comment by ThunderEX** [comment]
I think cpython-uasyncio is just a normal cpython package, it won't/never work with micropython. So just kick it out of micropython-lib repo into another seperate repo makes sense.

**Comment by jonnor** [comment]
cpython-uasyncio is no longer relevant, for several years now.
