### ISSUE TITLE
urequest memory leak

### ISSUE THREAD

**Issue by rarrr** [micropython/micropython-lib#151]
Been going around in circles with this one, not found an answer anywhere.  Appears the heap gets fragmented and is unable to allocate more space.  However not matter if you do a POST, GET, supply headers or change the length of the address it returns the error after 43 attempts.

test.html is blank
after 43 requests below error is given.

Using esp8266-20170108-v1.8.7 and an ESP-01s

>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "req.py", line 7, in <module>
>  File "urequests.py", line 101, in get
>  File "urequests.py", line 57, in request
>OSError: [Errno 12] ENOMEM

>import urequests
>t = 0
>while True:
>    t = t + 1
>    print(t)
>    urequests.get('http://192.168.1.3/test.html')
>print("done")`

**Comment by pfalcon** [comment]
You need to .close() response you get from urequests.get() (and any network socket in  general).
