### ISSUE TITLE
umqtt: publishing to disconnected client object resets an esp8266 board

### ISSUE THREAD

**Issue by larsks** [micropython/micropython-lib#152]
Given this code:

```
>>> from umqtt.simple import MQTTClient
>>> c = MQTTClient('mysep', '192.168.1.69')
>>> c.publish(b'foo_topic', b'a message')
>>> c.disconnect()
>>> c.publish(b'foo_topic', b'a message')
```

My board immediately resets:

```
Fatal exception 28(LoadProhibitedCause):
epc1=0x4026464e, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000070, depc=0x00000000

 ets Jan  8 2013,rst cause:4, boot mode:(3,0)

wdt reset
```

I'm running MicroPython v1.8.7-232-gf2d732f on a DigiStump Oak (ESP8266, `esp.flash_size()` reports 4194304)

**Comment by dpgeorge** [comment]
This is a general bug concerning writing to a closed socket (that was once connected), and happens not just for MQTT.  Ideally it would be reported and discussed upstream at https://github.com/micropython/micropython
