### ISSUE TITLE
micropython-uasyncio version on github and pypi server are not matching.

### ISSUE THREAD

**Issue by cwyark** [micropython/micropython-lib#160]
I tried to download 'micropython-uasyncio' package from pypi server and I see the following output.

```
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== import logging
=== #logging.basicConfig(level=logging.INFO)
=== logging.basicConfig(level=logging.DEBUG)
=== loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "uasyncio/core.py", line 175, in get_event_loop
TypeError: __init__() takes 1 positional arguments but 2 were given
>>>
```

After I check the package version on micropython-lib repository and pypi server.
I found version on github is v1.1.1 and pypi is still v1.1. but the dependency pkg 'micropython-uasyncio.core' has been push to v1.1.1.
I guess uasyncio and uasyncio.core version are not matching on current pypi server.

**Comment by pfalcon** [comment]
Thanks for the report. Weird. I usually upload new version immediately after I push a version-bump commit, must have been an error during upload which I didn't notice. Uploaded now: https://pypi.python.org/pypi/micropython-uasyncio/1.1.1
