### ISSUE TITLE
[Errno 103] ECONNABORTED MQTT

### ISSUE THREAD

**Issue by yigibihe** [micropython/micropython-lib#162]
Hello,

I flashed the last stable of micropython to my ESP-01 1mb with esptool. I connected to it the wifi, I can ping the esp from my mqtt server. 

Esp is fed from external power and extra 1000uf capacitor was added for extra stability. I reflashed the module.

```
>>> print(sta_if.ifconfig())
('192.168.4.55', '255.255.255.0', '192.168.4.1', '192.168.4.1')
>>> from umqtt.simple import MQTTClient
>>> c = MQTTClient("umqtt_client", "192.168.4.10")
>>> c.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "umqtt/simple.py", line 56, in connect
OSError: [Errno 103] ECONNABORTED
>>> c.ping()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "umqtt/simple.py", line 94, in ping
OSError: [Errno 103] ECONNABORTED
>>> import esp
>>> esp.check_fw()
size: 586684
md5: 2c7ce68f0e1a5690257698e5e42caf16
True
```

**Comment by dmascord** [comment]
What MQTT broker is running on 192.168.4.10 ?   umqtt.simple implements MQTT Version 3.11.  Have you tested the broker with another MQTT client with version 3.11 enabled ?

**Comment by marev3** [comment]
Hello,

same here.

on my esp8266 with micropython 1.9.2 I tried:
```
from umqtt.simple import MQTTClient
c = MQTTClient("esp8266", "192.168.1.116")
c.connect()
```

and got:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "umqtt/simple.py", line 56, in connect
OSError: [Errno 103] ECONNABORTED
```
The server running on 192.168.1.116 is mosquitto 1.3.4 (which should support mqtt 3.1.1) and is working with another client (publishing and subscribing).

What else can I try?

**Comment by dmascord** [comment]
Could you try enabling authentication on mosquitto ?  It could be that there is a malformed MQTT packet when authentication is not on

**Comment by marev3** [comment]
In the meantime I installed the newest version 1.4.14 of mosquitto that didn't change that error.

> Could you try enabling authentication on mosquitto ?

How do I configure that?

**Comment by dmascord** [comment]
https://medium.com/@eranda/setting-up-authentication-on-mosquitto-mqtt-broker-de5df2e29afc
seems like a decent howto

**Comment by marev3** [comment]
Okay, I enabled authentication on the mosquitto server, that is working fine.

On the esp8266 I tried it with:
```
from umqtt.simple import MQTTClient
c = MQTTClient(client_id = "esp8266", server = "192.168.1.116", port = 1883, user = b"hallo", password = b"test")
c.connect()
```

and still get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "umqtt/simple.py", line 56, in connect
OSError: [Errno 103] ECONNABORTED
```

**Comment by marev3** [comment]
I found out that I accidentally had connected the esp8266 to my guest wifi instead of the wifi in which my mosquitto server is.
So my problem is solved.

**Comment by TJaenichen** [comment]
Thanks... that could have taken a while

**Comment by jonnor** [comment]
Problem solved, issue should be closed.
