### ISSUE TITLE
uasyncio: awrite and non ascii strings

### ISSUE THREAD

**Issue by fstengel** [micropython/micropython-lib#187]
While playing with picoweb I discovered this:

asyncio.awrite consitently fails when given a non ascii string: the assert on line 154 fails showing that more bytes have been sent than the length of the given string. Which is obvious: `"é"` is two bytes long in utf8 but a one character string...

Somehow usocket.write does see a string as its utf8 bytes (or any representation that makes "é" two bytes or more long) and therefore sends more bytes than the string length.

Would it not be better to (silently) convert (using what encoding?) a string to a bytes buffer and then write that buffer? A bytes buffer would be sent as is.

I am using micorpyton 1.9 on an esp8266

**Comment by pfalcon** [comment]
Both sockets and uasyncio work only on byte strings. Behavior on strings is undefined. (So don't pass them there.)
