### ISSUE TITLE
urequests induces esp8266 crash with a message LmacRxBlk:1

### ISSUE THREAD

**Issue by disassembly** [micropython/micropython-lib#232]
I am using micropython on an esp8266 board, when I use urequests to post data to 2 different servers, after serval loops, esp8266 crashes with this message LmacRxBlk:1, need to  hard reset the board to make it work again.
The code is like this:
while True:
        r1 = urequests.post(SOME_URL,headers=xxx,data=xxxx)
        r2= urequests.post(SOME_URL_1,headers=xxxx,data=xxxx)
       time.sleep(300)
But if I post data to only 1 server, it never comes to the crash LmacRxBlk:1.
Does anybody know why?

**Comment by pfalcon** [comment]
Please read the docs: http://docs.micropython.org/en/latest/esp8266/esp8266/general.html#sockets-and-wifi-buffers-overflow
