### ISSUE TITLE
datetime implementation

### ISSUE THREAD

**Issue by xrmx** [micropython/micropython-lib#233]
Opened the issue to avoid other people trying to port Cpython's pure python datetime
implementation and find out that is blocked by the following micropython issue: https://github.com/micropython/micropython/pull/3391

That specific datetime implementation needs:

- time.strptime

And cpython tests need:

- decimal.Decimal
- test.support.is_resource_enabled
- test.support.requires_IEEE_754
- test.support.run_with_tz
- random.randrange (aliasing urandom)

**Comment by pfalcon** [comment]
As the quoted ticket hints, I have the patches in my tree, and will push the for review (or directly to the repo) when other things in the queue are processed.

**Comment by xrmx** [comment]
Cool, thanks! is there any of the requirements that has not been developed yet?

**Comment by pfalcon** [comment]
So, I pushed the baseline CPython files to master, then https://github.com/micropython/micropython-lib/pull/234 presents my current patchset on top of that.

**Comment by pfalcon** [comment]
randrange() is discussed in https://github.com/micropython/micropython-lib/pull/208

**Comment by pfalcon** [comment]
Merged to mainline.

**Comment by xrmx** [comment]
Thanks!
