### ISSUE TITLE
Ctrl-C in select.epoll.poll() leads to crash on 32-bit x86

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython-lib#24]
I have the following test code:
```
import select
epoll = select.epoll()
epoll.register(0, select.EPOLLIN)
epoll.poll()
```
It'll wait until there's data on stdin to read.  If you press ctrl-C then the poll returns with EINTR and is supposed to finish early.  On 64-bit x86-64 it works as expected (KeyboardInterrupt is raised) but on 32-bit x86 it leads to seg fault.

Any ideas?

**Comment by pfalcon** [comment]
See also: https://github.com/micropython/micropython/issues/1035

**Comment by pfalcon** [comment]
Fixed by https://github.com/micropython/micropython/commit/3db2b230602b0140b3ea430c61d415335d939274

**Comment by dpgeorge** [comment]
I can confirm that it's fixed.  Great!
