### ISSUE TITLE
uasyncio.synchro synchro.py appears to have a typo

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython-lib#240]
It seems that [this line](https://github.com/micropython/micropython-lib/blob/c279a8195fbda91b796d90de500c8ab1530fed01/uasyncio.synchro/uasyncio/synchro.py#L27) should read
```
            self.wlist.append(core.get_event_loop().cur_task)
```

**Comment by pfalcon** [comment]
Yes, that var was renamed upstream. Fixed, thanks for report.
