### ISSUE TITLE
[STM32F407] ImportError: no module named 'ussl'

### ISSUE THREAD

**Issue by nikhil1983** [micropython/micropython-lib#245]
Hey, 
I am using Ubuntu OS. I am currently working on STM32F407disc board.
While importing module ' upip ' in micropython, it gives me an error of ussl module not found. 

> >>> import upip
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "upip.py", line 102, in <module>
> ImportError: no module named 'ussl'
> >>> import upip
> >>> upip.install("micropython-uasyncio")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'module' object has no attribute 'install'
> >>> 

Can anyone tell me where i will get this ussl module ?

**Comment by amotl** [comment]
Hi there,

while developing the [hiveeyes-micropython-firmware](https://github.com/hiveeyes/hiveeyes-micropython-firmware), we are currently experiencing the same problem on a recent ArchLinux system:
```
micropython -m upip install -p dist-packages -r requirements-mpy.txt
Traceback (most recent call last):
  File "upip.py", line 109, in <module>
ImportError: no module named 'ussl'
```

Do you have any idea where this might coming from and how to mitigate it?

With kind regards,
Andreas.

**Comment by dhylands** [comment]
MICROPY_PY_USSL doesn't appear to be defined for any of the stm32 boards, so you'll need to add that to your board file (mpconfigboard.py)

There may be additional #defines which need to be made as well to select the SSL implementation. I see that the esp8266 port and the unix port both define MICROPY_PY_USSL = 1

**Comment by jonnor** [comment]
As mentioned, one may have to enable SSL in a MicroPython firmware build. This is because of size constraints.
