### ISSUE TITLE
pypi redirects to https://pypi.org/pypi/%s/json and brakes upip

### ISSUE THREAD

**Issue by davidkwast** [micropython/micropython-lib#274]
Changing URL to "https://pypi.org/pypi/%s/json" appears to fix but I can't test now yet because I don't have the build process setup yet.

A put modified upip.py inside the flash memory but my ESP8266 board do not have enough ram to run upip.install

```
>>> upip.install('micropython-urequests')
Installing to: /lib/
Warning: pypi.python.org SSL certificate is not validated
Error installing 'micropython-urequests': b'302', packages may be partially installed
```

**Comment by drosenbauer** [comment]
Thank you, I thought I was going nuts. What's the process for this getting migrated into an official esp8266 build?

**Comment by peterhinch** [comment]
I've updated [micropip](https://github.com/peterhinch/micropython-samples.git) which now works again, so at least there is a way to access libraries until upip is fixed.

**Comment by pfalcon** [comment]
I'm personally busy with real life to look into this so far.

**Comment by dpgeorge** [comment]
Yes it's broken.  pypi.python.org was turned off on 13th April 2018 and pypi.org is now the URL to use; see https://packaging.python.org/guides/migrating-to-pypi-org/

**Comment by di** [comment]
I've made a PR to fix this: https://github.com/micropython/micropython-lib/pull/275 (I'm also a PyPI contributor/maintainer/administrator if that helps lend credibility to the patch).

**Comment by dpgeorge** [comment]
This is now fixed in micropython-lib.
