### ISSUE TITLE
How to startup Umqtt  on an ESP8266

### ISSUE THREAD

**Issue by gkhan1234** [micropython/micropython-lib#285]
I'm fairly new to this so please be patient. I have Mosquitto PI setup and working I tested a simple python by using ESPlorer "send to ESP" This works. How can I this to startup automatically. I need the script living on the EPS8266. Please, any help would be greatly appreciated.

**Comment by dpgeorge** [comment]
Please ask these kind of "how to" questions on the forum at: https://forum.micropython.org.  Thanks.
