### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by Sushma310** [micropython/micropython-lib#290]
I am facing an issue with 'publish' function in umqtt.simple. It is showing 
    AttributeError: 'NoneType' object has no attribute 'write'

can you please tell me the solution for this?

**Comment by dpgeorge** [comment]
Please provide more information to diagnose the problem: MicroPython port and hardware used, version of MicroPython, version of umqtt, and line number of the error.

But, it looks like you can only get this kind of error if there is no network available.

**Comment by wojsudol** [comment]
for the record. I had this error message when I was trying subscribe channel before connect to server.

nok:
``` python
    mqtt.subscribe(channel_url)
    mqtt.connect()
```

ok:
``` python
    mqtt.connect()
    mqtt.subscribe(channel_url)
```
