### ISSUE TITLE
Network Status ESP32

### ISSUE THREAD

**Issue by fernandomorse** [micropython/micropython-lib#305]
ESP32
version 1.9.4

`network.status()
`

always return None

**Comment by dpgeorge** [comment]
This was recently implemented here: https://github.com/micropython/micropython/commit/385fa5180663221bbec033c54c37fb38f589579b

**Comment by fernandomorse** [comment]
@dpgeorge 

I checked that

```
from network import WLAN
wlan = WLAN ()
wlan.status ()
wlan.isconnected ()
wlan.isconfig ()

```
result:

```
1010
True
('10 .1.2.141 ',' 255.255.255.0 ', '10 .1.2.1', '10 .1.2.1 ')

```
turn off my router

result:

```
1010
True
('0.0.0.0', '0.0.0.0', '0.0.0.0', '10 .1.2.1 ')
```

status() e ifconfig() not changed.

thanks
