### ISSUE TITLE
ESP32 WLAN not modify information

### ISSUE THREAD

**Issue by fernandomorse** [micropython/micropython-lib#306]
Reference #305 

I checked that

from network import WLAN
wlan = WLAN ()
wlan.status ()
wlan.isconnected ()
wlan.isconfig ()

result:

1010
True
('10 .1.2.141 ',' 255.255.255.0 ', '10 .1.2.1', '10 .1.2.1 ')

turn off my router

result:

1010
True
('0.0.0.0', '0.0.0.0', '0.0.0.0', '10 .1.2.1 ')
status() e isconnected() not changed.

thanks

**Comment by tlvlp** [comment]
Just came across this issue by accident. This problem has been resolved recently in the latest official MicroPython releases.
https://github.com/micropython/micropython/commit/21f9329d5d69516064f0ad77af311ac31a6dd009

**Comment by jonnor** [comment]
Issue has been fixed 5 years ago.
