### ISSUE TITLE
Micropython-lib uu has no attribute "b2a_uu"

### ISSUE THREAD

**Issue by vvg123** [micropython/micropython-lib#307]
I trying to use `uu` for encode/decode some file in `Micropython` but failed due to 
### 1. No Attribute 'b2a_uu'
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "uu.py", line 87, in encode
  File "uu.py", line 82, in encode
AttributeError: 'module' object has no attribute 'b2a_uu'
```
Is that `uu` module missing out `b2a_uu` in Micropython?

By the way the code is correct as below?
`uu.encode("Ori.file", "Encoded.file", "/")`

### 2. Can't convert 'int' object to str implicitly
```
import uu
>>> uu.encode("Ori.file", "Encoded.file", "/", "/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "uu.py", line 87, in encode
  File "uu.py", line 79, in encode
TypeError: can't convert 'int' object to str implicitly
```
Or this `uu` module is still under developing?

**Comment by SpotlightKid** [comment]
The only functions in the `uu` [module](https://github.com/micropython/micropython-lib/blob/master/uu/uu.py) are `encode` and `decode` (and `test`), as in the [documented API](https://docs.python.org/3/library/uu.html) of the CPython equivalent.

The `b2a_uu` function is supposed to come from the `binascii` module, but, alas, neither the micropython-lib implementation of this module, nor the builtin-in `ubinascii` module of MicroPython provides this function.

It seems that the `uu` module in micropython-lib was just copied from the CPython standard library without adapting it to MicroPython or testing whether it actually works. There are several other places in the code, which will not work with micropython-lib, e.g. use of `os.path` and `optparse`. So it is not in a usable state at the moment.

**Comment by vvg123** [comment]
Yah, sad to know that though can use for encode some files inside Micropython. So I will close this issue then. Thanks of your reply.

**Comment by vvg123** [comment]
Or is that other alternative to encoding inside Micropython?

**Comment by SpotlightKid** [comment]
Does it need to be uuencoding? Why not just use base64 encoding (`ubinascii.b2a_base64()`)

**Comment by vvg123** [comment]
Oh yah, I mess up the different of the `uu` and the `base64`. They are different things, thanks for pointing out, haha.
