### ISSUE TITLE
No module named uasyncio - PyBoard V1.1

### ISSUE THREAD

**Issue by rlnktt** [micropython/micropython-lib#308]
I have been looking to give 'uasyncio' a try. But whenever I try to import the module in the PyBoard that I use, I get this weird import error saying 'no module named uasyncio'.

Am I lagging any additional package installations 

Any help is greatly appreciated!!
![sshot_uasyncio](https://user-images.githubusercontent.com/41668475/45916697-0dbb2b80-be88-11e8-9961-f7b32ee1f198.jpg)

**Comment by kimothokamau** [comment]
If you run help ('modules') you should see uasyncio/core uasyncio/queues and uasyncio/synchro as in the attached image. If they don't exist it means they are not included in your firmware, you need to download them and recompile your firmware.

**Comment by jonnor** [comment]
Recent versions of MicroPython for stm32/pyboard should include asyncio. If the issue persists on 1.23+ or later, please re-open with details of which firmware build you use.
