### ISSUE TITLE
a problem with the publication

### ISSUE THREAD

**Issue by novikovav69** [micropython/micropython-lib#309]
Hello!
I have a problem with the publication.
I do:
from umqtt.simple import MQTTClient
client = MQTTClient(client_id="ESP8266", server="192.168.100.10", port=1883)
client.connect
client.publish("in", "sHOW")

I receive:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "umqtt/simple.py", line 123, in publish
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by SpotlightKid** [comment]
@novikovav69 `MQTTClient.connect` is a method, you need to call it.You are missing the parentheses after `client.connect`.

**Comment by novikovav69** [comment]
Many thanks! Forgive me my carelessness.
