### ISSUE TITLE
urequests - header dict not being passed through correctly?

### ISSUE THREAD

**Issue by eymas** [micropython/micropython-lib#314]
I'm at a loss regarding the following:
```
import urequests as requests
import ujson

method = "get"
url = "https://api.example.com"
headers = {
    "authorization": "Bearer" + token,
    "accept": "application/json"
    }
result = requests.request(method, url, headers)
result_obj = ujson.loads(result.json())
```
Looking at the request function within urequests.py, I believe I do have to pass a dictionary onto headers. However; the following is returned when I do so: `TypeError: object with buffer protocol required`

If I pass on the headers within the function call. I get a Bad Request error and no other way to read the response object to determine the exact cause.

**Comment by SpotlightKid** [comment]
I think all header keys and values need to be byte strings, i.e. `bytes` not `str`.

**Comment by eymas** [comment]
Having added a quick encoder the error still repeats, unfortunately:
`header = ujson.dumps(headers).encode('utf-8')`
