### ISSUE TITLE
umqtt.robust sends the NodeMCU Esp8266 board in some freezing state

### ISSUE THREAD

**Issue by JDchauhan** [micropython/micropython-lib#316]
I have observed some strange problem in my NodeMCU Esp8266 board after running umqtt.robust that the board will stop silently without any warning or throwing errors after 10-15 minutes of no communication with the broker (i.e, if the client does not publish or receive any message of subscribed topics for 15 minutes approx.).

It seems like the library might be taking the board to some blocking state.

Please check and fix that issue.

**Comment by jonnor** [comment]
Hi. There is unfortunately not enough information here to reproduce or debug this problem.

Multiple issues with mqtt on esp8266 have been fixed over the last 5 years. And some are still open - search the issue tracker for more. Please re-test on the latest versions and if there are still problems which are not described in already open issues, provide details such as a minimal code example for how to reproduce - along with details about the MQTT setup, such as broker version.
