### ISSUE TITLE
datetime 'tzinfo' has no attribute '__new__'

### ISSUE THREAD

**Issue by rdagger** [micropython/micropython-lib#319]
When I try to import datetime using latest build of LoBo MicroPython I get the following error:

> >>> import datetime
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "datetime.py", line 1919, in <module>
>   File "datetime.py", line 1836, in _create
> AttributeError: type object 'tzinfo' has no attribute '__new__'
> >>>

**Comment by rdagger** [comment]
I also tested with the latest Micropython.org build esp32spiram-20181109-v1.9.4-683-gd94aa577a.bin
It produces the same error message as the LoBo build.

**Comment by YTBeater** [comment]
@miguelgrinberg Thanks you for your fixes. That work for me too.

**Comment by stroobandt** [comment]
@miguelgrinberg Thanks for the fix Miguel. That works here too.

**Comment by jonnor** [comment]
This seems to have been fixed. 
Using MicroPython 1.23 and the Unix port, I can successfully import datetime.

micropython -m mip install datetime
```python
import datetime
```

**Comment by projectgus** [comment]
Yes, I think this code got rewritten in fc86070ffb8aeea.
