### ISSUE TITLE
umqtt.robust is missing an example file

### ISSUE THREAD

**Issue by mlpilla** [micropython/micropython-lib#320]
In line 23 of umqtt.robust/example_sub_robust.py, there is a mention of example_reset_session.py. I could not find this file.

**Comment by jonnor** [comment]
No-one has found the file in 5 years. Then it is probably not surfacing now, unfortunately. Proposing to close this issue.

**Comment by projectgus** [comment]
I think the least we can do here is remove the reference to the missing example. If someone wants to contribute an example of how to do this in the future then it would be very welcome.
