### ISSUE TITLE
utarfile  error

### ISSUE THREAD

**Issue by 23233** [micropython/micropython-lib#322]
##  erorr code 
```
f1 = tarfile.TarFile("test.zip")
<TarFile object at 3ffec980>

f1.next() 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "local_lib/utarfile.py", line 88, in __next__
  File "local_lib/utarfile.py", line 78, in next
UnicodeError: 


bytearray(b'PK\x03\x04\n\x00\x00\x00\x00\x00\x93\x98\xf0L\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\t\x00gosignaler-master/UT\x05\x00\x01\xb7NM[PK\x03\x04\n\x00\x00\x00\x00\x00\x93\x98\xf0L\xebu\xd3\x04!\x00\x00\x00!\x00\x00\x00\x1c\x00\t\x00gosignaler-ma')

in 89 line code is 

 d.name = str(h.name, "utf-8").rstrip("\0")

```

**Comment by dhylands** [comment]
TarFile is for extracting tar files not zip files. I'm not sure anyone had written a zip file extracted. The core compression algorithm is available in uzlib.

**Comment by 23233** [comment]
**@dhylands  Thank you replay my question ！**

but i'm try to extractor a tar files , error same!!

please help me 
 
i don't know how about and how to work~ 

thanks you 

hardware：esp32
firmware：1.9.1
tar files : create test.py files,write some line,  run  tar zcvf test.tar.gz test.py

**Comment by dhylands** [comment]
.tar.gz is a tar file that has been compressed. Try just a plain tar file.

**Comment by 23233** [comment]
nice create a tar file this is working ~~

tar -cf test.tar test.py

thanks @dhylands !!!
