### ISSUE TITLE
urequests iter line

### ISSUE THREAD

**Issue by DavidM42** [micropython/micropython-lib#327]
Is there some way to gradually read a response from a requests get? I'm trying to fetch a json resource via a get request with authorization header and I'm receiving an insufficient memory error on an esp8266.
Is there some way to add a method like response.iter_line to urequests to support reading the respone line by line for lower memory use?

**Comment by pfalcon** [comment]
See http://docs.python-requests.org/en/master/user/quickstart/#raw-response-content and the source code.
