### ISSUE TITLE
"ValueError: generator already executing" as a result of exhausted heap on ESP8266

### ISSUE THREAD

**Issue by eltomek** [micropython/micropython-lib#333]
uasyncio encounters an issue and interrupts program execution at the coroutine's
`await asyncio.sleep(delay_secs)`
line with 
`ValueError: generator already executing`
when the available heap size drops below ~10500 bytes at ESP8266 (Wemos D1 mini board).

As a workaround, one can either force garbage collector to collect as often as possible (`gc.collect`) or increase GC's sensitivity by setting the `gc.threshold`'s parameter empirically.

Interestingly, as a follow up, I checked the gc.threshold(-1) to disable allocation threshold and then heap goes to as low as 400 bytes even not causing the issue described above. So, not sure if I nailed this problem right unfortunately.

See https://forum.micropython.org/viewtopic.php?f=15&t=85&p=34496#p34496 for more info.

Error message:
```
Traceback (most recent call last):
  File "main.py", line 233, in <module>
  File "picoweb/__init__.py", line 298, in run
  File "uasyncio/core.py", line 154, in run_forever
  File "uasyncio/core.py", line 109, in run_forever
  File "main.py", line 223, in mem
ValueError: generator already executing
```
where "main.py", line 223, in mem is:
`await asyncio.sleep(delay_secs)`
"main.py", line 233, in <module> is:
`loop.create_task(mem(1))`

**Comment by eltomek** [comment]
Seems like it's strongly related to MQTTClient object creation, need to investiage more before logging a defect.

**Comment by devbis** [comment]
Thanks for the investigation. Are you sure that this is caused by exhausted heap?
I quite regularly can see this exception, but I use deep sleep with a short working cycle. So it is quite weird that heap exhausting randomly.

**Comment by eltomek** [comment]
It is likely unrelated to uasyncio itself however it very much helps to run it within uasyncio. I have performed dozens of tests to see which part of my code caused the issue and pinned this:

`            client = MQTTClient(client_id=myMqttClient, 
                                server=THINGSPEAK_URL, 
                                user=THINGSPEAK_USER_ID, 
                                password=THINGSPEAK_MQTT_API_KEY, 
                                ssl=False)

            client.connect()  # <- this part generates issues when the heap is running low, but not always. 
`
`gc.collect()` seems to be just a workaround, but at least worked for me, right now I will be running the script for 3 weeks continuously, will see if it will make it.
