### ISSUE TITLE
from pkg_resources import load_entry_point

### ISSUE THREAD

**Issue by PYTOMPY** [micropython/micropython-lib#337]
Hi all,
I have successfully added micropython-lib into my VM. But while executing my deamon its throwing an error which says "from pkg_resources import load_entry_point" is not available. Can anyone help me in rectifying this error

**Comment by dpgeorge** [comment]
What exactly is the issue here?

**Comment by PYTOMPY** [comment]
load_entry_point is not available!! In python pkg_resources contain a function load_entry_point. But this is not available in micropython. Is there any equivalent function for this?

**Comment by dpgeorge** [comment]
> But this is not available in micropython. Is there any equivalent function for this?

No there isn't an equivalent function for this.  You'll need to find a way around it, possibly by implementing your own version of the function.

**Comment by PYTOMPY** [comment]
thanks
