### ISSUE TITLE
Module re gives ValueError: Error in ffi_prep_cif

### ISSUE THREAD

**Issue by hacksterous** [micropython/micropython-lib#339]
On MicroPython on Ubuntu-x86, when I import 're' from the REPL, I get 
`ValueError: Error in ffi_prep_cif `

```
MicroPython v1.10-291-g27d22d871-dirty on 2019-05-03; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import re
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user0/.micropython/lib/re.py", line 11, in <module>
ValueError: Error in ffi_prep_cif
>>>
```
I have installed 're' using `upip`
```
./micropython -m upip install micropython-re-pcre
```

**Comment by jonnor** [comment]
This module is now called `re`, at https://github.com/micropython/micropython-lib/blob/master/unix-ffi/re/re.py
Please re-test on a recent MicroPython version
