### ISSUE TITLE
Pickle is not dummy anymore

### ISSUE THREAD

**Issue by iBobik** [micropython/micropython-lib#340]
> Dummy pickle module for MicroPython

https://pypi.org/project/micropython-pickle/
https://github.com/micropython/micropython-lib/blob/master/pickle/setup.py#L11

**Comment by iBobik** [comment]
It is description ok?

> Easily dump python objects to files, and then load them back.

**Comment by jonnor** [comment]
The current pickle module is found at https://github.com/micropython/micropython-lib/tree/66fa62bda10d199be5b24457e044cb863d5d216a/python-stdlib/pickle

Feel free to open merge requests for improving the package metadata and/or a README file.
