### ISSUE TITLE
urllib.parse seems not be "micro"

### ISSUE THREAD

**Issue by iBobik** [micropython/micropython-lib#341]
[urllib.parse](https://github.com/micropython/micropython-lib/blob/master/urllib.parse/urllib/parse.py) seems like it has not been ported to Micropython (uses collection etc.) and generally seems not to be "micro".

Should it be there in this state?

**Comment by jonnor** [comment]
urllib.parse has been moved to unix-ffi, so it is only available on the Unix port. This signals strongly that it is not suitable for microcontroller usage. Proposing to close this issue.
