### ISSUE TITLE
In the 1.11 version of Micropython  the 'sys' library has no exec_info() method

### ISSUE THREAD

**Issue by nherriot** [micropython/micropython-lib#352]
In line 67 there is a call to sys.exc_info(...) shown below.

https://github.com/micropython/micropython-lib/blob/b89114c8345e15d360c3707493450805c114bc8c/logging/logging.py#L67

However this will not work on the latest version of micropython as the sys library does not have this method compiled in. e.g.

```bash
>>> import sys
>>> sys.
__class__       __name__        argv            byteorder
exit            implementation  maxsize         modules
path            platform        print_exception
stderr          stdin           stdout          version
version_info
```
Furthermore, there is not mention of the exec_info method on [docs](http://docs.micropython.org/en/latest/library/sys.html). 

I suggest removing this example and replace with a working direct call to:
   **_sys.print_exception(e,stream)_**
which needs to have the exception object passed in.

In the long term maybe this method can be added.

**Comment by jonnor** [comment]
The latest version of the logging modules does not reference exec_info anymore. So this can be closed
