### ISSUE TITLE
problem with http.client module

### ISSUE THREAD

**Issue by Diallomm** [micropython/micropython-lib#356]
when i call **HTTPConnection** on import module i have this error on shell 

----
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name HTTPConnection

**Comment by jonnor** [comment]
Please use either `requests` or `aiohttp` for HTTP client. The HTTPConnection code is unix only, and should not generally be used.

Also, when reporting issue, please include the code that you run. Otherwise it is impossible to reproduce or debug the problem.
