### ISSUE TITLE
ilistdir file mode listing incorrect

### ISSUE THREAD

**Issue by bradley499** [micropython/micropython-lib#361]
Mode validation for directory is invalid (present and only tested on linux/unix port) mode returned by ilistdir is ```32768```; which is not referenced as a directory; however this is still returned on files that are directories. Was found when trying to use os.walk from the linked file below; it returns everything in the current directory as a file, as dictated by the file mode type; as verification in stat returns the type as not a directory. Is this to be fixed?

[https://github.com/micropython/micropython-lib/blob/master/os/os/__init__.py#L147](https://github.com/micropython/micropython-lib/blob/master/os/os/__init__.py#L147)

**Comment by jonnor** [comment]
There appears to be a fix for this issue in the linked commit. If this is not the case, please re-open this issue with some code that demonstrates the issue on latest MicroPython + os module.
