### ISSUE TITLE
Missing file libsqlite3 from sqlite3

### ISSUE THREAD

**Issue by ASH247iT** [micropython/micropython-lib#372]
Hi All
I was interested in using the micropython sqlite3 which looks like a wrapper around a C library
libsqlite3 - which I cannot find. Could this be included in the repo please ?
Line 5       :      sq3 = ffilib.open("libsqlite3")
https://github.com/micropython/micropython-lib/blob/master/sqlite3/sqlite3.py
Many Thanks

**Comment by mattytrentini** [comment]
FFI is only supported on the unix port - and to use sqlite3 on the unix port it must be installed on your system. On Debian for example: `apt install sqlite3`.

Alternatively, if you'd like to try sqlite on MicroPython (including on devices) without using FFI then do take a look at https://github.com/spatialdude/usqlite.
