### ISSUE TITLE
ES8266 upip cannot install packages from PyPi

### ISSUE THREAD

**Issue by rvalle** [micropython/micropython-lib#373]
Hi!

I am new to micropython, I am testing to install packages from PyPI directly on target. The idea is to use upip as the tool to download and install our software on the target.

on the Unix port I can install for example the package micropython-scron
```
$ docker run -it mitchins/micropython-linux
MicroPython v1.12-248-g86bfabec1 on 2020-03-11; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import upip
>>> upip.install("micropython-scron")
Installing to: /root/.micropython/lib/
Warning: micropython.org SSL certificate is not validated
Installing micropython-scron 0.8.0 from https://files.pythonhosted.org/packages/19/e8/a0389d7e156245f45f4a0d0705b6529bbace88d5b691369fac7326768c69/micropython-scron-0.8.0.tar.gz
```
However when I try to do the same on target:

```
WebREPL daemon started on ws://0.0.0.0:8266
Started webrepl in normal mode
Hello World from Celpax

MicroPython v1.12 on 2019-12-20; ESP module with ESP8266
Type "help()" for more information.
>>> 
>>> import upip
>>> upip.install("micropython-scron")
Installing to: /lib/
Warning: micropython.org SSL certificate is not validated
Error installing 'micropython-scron': , packages may be partially installed
```
upip seems, on target,  to be hardcoded to only fetch micropython-lib packages, which I find hard to believe, and also checking past upip issues I can see downloads from pypi.org on target.

So, what is it that I am getting wrong?

**Comment by andrewleech** [comment]
Sorry you didn't get feedback at the time, but now Micropython has recently rolled out a new packaging tool called `mip`, for details see https://docs.micropython.org/en/latest/reference/packages.html

This supports installation of packages from custom sources.
