### ISSUE TITLE
Allow upip to install from custom URLs (not just pypi.org)

### ISSUE THREAD

**Issue by redstreet** [micropython/micropython-lib#404]
It would be great if upip supported private repos outside pypi.org. See [private-pypi](https://pypi.org/project/private-pypi/).

It looks like the code change is simple, to parameterize the website via an api like `upip.set_pypi_url()`, which will be used below:

https://github.com/micropython/micropython-lib/blob/eae01bd4e4cd1b22d9ccfedbd6bf9d879f64d9bd/upip/upip.py#L159

Would you entertain a PR for this if I submitted one? Thanks!

**Comment by andrewleech** [comment]
Micropython has recently rolled out a new packaging tool called `mip`, for details see https://docs.micropython.org/en/latest/reference/packages.html

This supports installing packages from custom repositories.
