### ISSUE TITLE
Is there any ECDSA implementation for Micropython?

### ISSUE THREAD

**Issue by parsa-fs** [micropython/micropython-lib#415]
I was wondering if there is any ECDSA implementation for Micropython, like the standard ECDSA lib for Python3 and 2.

**Comment by dmazzella** [comment]
I have published one my old implementation based on tomsfastmath
[ucrypto](https://github.com/dmazzella/ucrypto)

Let me know if it's of your interest.
D.

**Comment by parsa-fs** [comment]
Wohooo 🥳.
That's exactly what I wanted buddy, thanks a lot mate 🙏
