### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by willie5663** [micropython/micropython-lib#432]
Hello, I'm pretty new to Micropython in general so I'm not sure if this is an issue or just lack of understanding.

**But when running**
sudo pip install micropython-umqtt.simple

**I get the following output and error message:**
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting micropython-umqtt.simple
  Downloading https://files.pythonhosted.org/packages/bd/cf/697e3418b2f44222b3e848078b1e33ee76aedca9b6c2430ca1b1aec1ce1d/micropython-umqtt.simple-1.3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-QXWgXH/micropython-umqtt.simple/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-QXWgXH/micropython-umqtt.simple/

**Am I doing something wrong? Any direction would be helpful.**

**My setup is as follows:**
Developing on Raspbian GNU/Linux 10 (buster) installed on a RaspberryPi 3 B+
Developing for ESP8266
##Detecting chip type... ESP8266
##Chip is ESP8266EX
##Manufacturer: 68
##Device: 4016
##Detected flash size: 4MB

**Software version on raspberry pi:**
pip 18.1
bitstring-3.1.7 
ecdsa-0.17.0 
esptool-3.1 
reedsolo-1.5.4
setuptools-44.1.1
mpfshell-0.9.2 
websocket-client-0.59.0

On ESP8266
Micropython firmware: esp8266-20210618-v1.16

**Comment by jonnor** [comment]
MicroPython packages are not to be installed via `pip`. Instead the `mip` tool is used. Please see the official documentation: https://docs.micropython.org/en/latest/reference/packages.html
