### ISSUE TITLE
How to install libraries on pyboard?

### ISSUE THREAD

**Issue by bayesrule** [micropython/micropython-lib#45]
I know this must be a very rookie question, but I have to ask... I've managed to install micropython on my Mac and it can also connect with my pyboard and do some basic things through REPL. What should I do if I'd like to connect the pyboard with an IMU (e.g. MPU9250) and install revelant libraries onto pyboard so that the pyboard can automatically run the programme and send data once connected to a serial port.

Many thanks!

**Comment by pfalcon** [comment]
Sorry, this question isn't on-topic for micropython-lib. But it was discussed multiple times on http://forum.micropython.org/ , so please search there.
