### ISSUE TITLE
AIOBLE - Stuck on exhange MTU

### ISSUE THREAD

**Issue by steveli777** [micropython/micropython-lib#456]
in AIOBLE, when exchanging MTU, it will call ble.gattc_exchange_mtu() method, and wait for the Exchange_MTU event is back. 

And in some scenario, the peripheral will disconnect the central when receiving the MTU exchange request.

And at this moment, the Exhange_MTU event will never return. It causes the stuck.

**Comment by andrewleech** [comment]
I've addressed exactly this with a timeout argument added to mtu requests in https://github.com/micropython/micropython-lib/pull/465

**Comment by mattytrentini** [comment]
#465 resolves this issue, if there's more discuss on the issue lets do so there.
