### ISSUE TITLE
Undefined variable....

### ISSUE THREAD

**Issue by Enasynco** [micropython/micropython-lib#563]
https://github.com/micropython/micropython-lib/blob/d0f97fc218f07c381c835d9f632904c1ae1c9d6b/micropython/bluetooth/aioble/aioble/client.py#L278

Expect this is meant to be _FLAG_WRITE without a S

**Comment by jimmo** [comment]
Thanks! See https://github.com/micropython/micropython-lib/pull/564

**Comment by dpgeorge** [comment]
Fixed by 50b7aca1717291e2b7bb5f423661105545ab9054
