### ISSUE TITLE
AttributeError: 'module' object has no attribute 'sha512'

### ISSUE THREAD

**Issue by abuvanth** [micropython/micropython-lib#577]
hashlib library has no sha512

**Comment by jimmo** [comment]
Can you please provide more information. Which library are you using (a short code example showing how you see the problem), how did you install it, what version of micropython, etc.

There were some fixes relating to this earlier this year but need to see what you're doing first.

**Comment by abuvanth** [comment]
<img width="810" alt="Screenshot 2023-01-12 at 10 12 16 PM" src="https://user-images.githubusercontent.com/20999104/212127823-2c6db0ec-6319-4fd7-9301-2ec97a40417d.png">

**Comment by jimmo** [comment]
@abuvanth It sounds like you have the built-in hashlib rather than the one from micropython-lib (which adds SHA512).
