### ISSUE TITLE
Installing "urequests" Package Fails

### ISSUE THREAD

**Issue by ab-tools** [micropython/micropython-lib#590]
Using [latest build](https://micropython.org/resources/firmware/wesp32-20221219-unstable-v1.19.1-779-g57bb1e047.bin) of MicroPython with the ESP32 board [wESP32](https://micropython.org/download/wesp32/) I try to install the package `urequests` using the command `mip.install("urequests")`.

This results in following error:
```
Installing urequests (latest) from https://micropython.org/pi/v2 to /lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mip/__init__.py", line 1, in install
  File "mip/__init__.py", line 1, in _install_package
  File "mip/__init__.py", line 1, in _install_json
  File "urequests.py", line 121, in get
  File "urequests.py", line 63, in request
AttributeError: 'module' object has no attribute 'IPPROTO_SEC'
```

Installing other packages using the `mip` package manager work fine.

Any idea what is wrong with this specific package?

Thanks in advance for any tip about this
Andreas

**Comment by jimmo** [comment]
`mip` uses `urequests` (as you can see from the stack trace), and you are using the latest build, so you already have the latest version of urequests.

I'm a bit confused what's going on though... I suspect your board has some different version of urequests.py installed? Nothing in micropython-lib uses `IPPROTO_SEC` so you must have code that isn't from micropython-lib.

**Comment by jimmo** [comment]
> OSError: -202

@ab-tools This is the error that you'd expect if the board isn't connected to the network.
