### ISSUE TITLE
umqtt.simple not working with Mosquitto broker 2.0.15

### ISSUE THREAD

**Issue by YeeMoone** [micropython/micropython-lib#638]
Hi!
umqtt.simple fails to connect to mosquito 2.0.15. It throws back MQTTException: 2.
My mosquitto log without any errors. The logs displayed are the same as when connecting to the server using the MQTT debugger(An app), so, maybe my mpy device is connected to mosquiro broker? But how to fix it?

By the way, my MQTT debugger was able to successfully connect to the mosquito without any errors, including publish and subscribe messages

my device: nodemcu-8266(12F) from Espressif
my mqtt server: Mosquitto broker 6.2.0 in homeassistant(VMware)

**Comment by basta** [comment]
Try setting  keepalive=60 as an argument for MQTTClient, that fixed it for me

**Comment by YeeMoone** [comment]
thanks, it's working for me too

**Comment by andrewleech** [comment]
As Mosquitto is very common, maybe it makes sense to raise the default timeout to that?

**Comment by basta** [comment]
Afaik it's caused by an update to mqtt protocol that requires this argument to be specified. It's not related to the default value. But I don't understand it much
