### ISSUE TITLE
os: musl incompatibility?

### ISSUE THREAD

**Issue by roger-** [micropython/micropython-lib#64]
There seems to be an incompatibility with musl related to `errno` (tested on OpenWrt). See details [here](https://forum.openwrt.org/viewtopic.php?pid=305741). 

(Reporting this on someone's behalf.)

**Comment by pfalcon** [comment]
Issue with errno compatibility with any libc was fixed a month ago or so. Please make sure that openwrt has up to date packages and that's what users use.

**Comment by pfalcon** [comment]
I've just tagged micropython-lib v1.0. So, @roger- , please make sure OpenWRT has micropython 1.5.2 and micropython-lib 1.0, and retest with those, the issues should be fixed. I'm closing this, please comment to reopen.

**Comment by roger-** [comment]
Ah, seems like the user didn't try the latest version.

Presumably the bug is fixed, will update and test.
