### ISSUE TITLE
utarfile: invalid syntax for integer with base 8

### ISSUE THREAD

**Issue by AuHau** [micropython/micropython-lib#684]
I am using [OTA library](https://github.com/mkomon/uota) that I have tweaked to get my firmware from Github Release Assets, which are packed into Tar file (`tar -czf source.tar.gz *`) using [Github Workflow](https://github.com/AuHau/projector-cabinet/blob/master/.github/workflows/release_please.yaml#L43). 

The new firmware is downloaded to the flash correctly but when it is about to be extracted, it fails with error: `invalid syntax for integer with base 8` coming from [extracting the file's size in `utarfile`](https://github.com/micropython/micropython-lib/blob/7128d423c2e7c0309ac17a1e6ba873b909b24fcc/micropython/utarfile/utarfile/__init__.py#L119). 

I have printed the byte arrays of the `h.size` and got: `bytearray(b'00000002264 \x00')`.
Then I tried to repack the `tar` on my Mac and reuploaded that to the device and suddenly all works, but noticed that the printed byte array of size is: `bytearray(b'00000002264 ')`. Eq. `\x00` is missing.

In the Github Actions it is packed on Ubuntu machine. Maybe there should be some sanitation of the bytearray?

**Comment by dpgeorge** [comment]
Thanks for the report.  Indeed utarfile reading is broken!  It was broken by 7128d423c2e7c0309ac17a1e6ba873b909b24fcc

Should be fixed by 0a5b63559421a791083cdfadfdba2633f34f4d65
