### ISSUE TITLE
where the 'uio' come from?

### ISSUE THREAD

**Issue by yingshaoxo** [micropython/micropython-lib#717]
When I look at the io module, it imported a module called 'uio'

But I did not found it anywhere, where that thing comes from?

**Comment by mattytrentini** [comment]
Until [very recently](https://github.com/orgs/micropython/discussions/12078), MicroPython used a 'u' prefix on a number of libraries to indicate that it was a subset - and sometimes _different_ - to the CPython library of the same name. 

Nightly builds, and the impending v1.21 release, will drop the 'u' prefix but provide backwards compatibility (ie `import uio` will continue to work though `import io` should be preferred).

**Comment by jonnor** [comment]
This question looks to be answered. Proposing to close this issue.
