### ISSUE TITLE
SDCard class constructor doesn't match documentation

### ISSUE THREAD

**Issue by rgov** [micropython/micropython-lib#745]
[Quoth the documentation](https://docs.micropython.org/en/latest/library/machine.SDCard.html#machine.SDCard),

```python3
class machine.SDCard(slot=1, width=1, cd=None, wp=None, sck=None, miso=None, mosi=None, cs=None, freq=20000000):
```

The code:

https://github.com/micropython/micropython-lib/blob/46748d2817d791212808337c0c708f131ec5c353/micropython/drivers/storage/sdcard/sdcard.py#L41-L42

Is this fallout from moving from `machine.SDCard` to `sdcard.SDCard`?

**Comment by jonnor** [comment]
Yes, the APIs are not entirely the same. This is because sdcard.SDCard is generic, supporting any SPI object as an input. 

Whereas the machine.SDCard generally uses port-specific hardware peripherals to do the job - often other peripherals than SPI.
