### ISSUE TITLE
In the _libc library, module ffi appears to be missing

### ISSUE THREAD

**Issue by salimfadhley** [micropython/micropython-lib#8]
It's the first line of _libc/__init__.py 

It looks like there's supposed to be a module called 'ffi', however it's not present in _libc, nor does it seem to be a builtin on the pyboard.

Is this supposed to be part of the _libc module, or some component I need to get from elsewhere?

**Comment by pfalcon** [comment]
This is very old issue, with modules mentioned having undergone various changes since the report. So, I'm closing it as out out of date. If you have a specific issue with current versions of micropython/micropython-lib, please submit a new report.
