### ISSUE TITLE
Please add tag for v1.22.2

### ISSUE THREAD

**Issue by Josverl** [micropython/micropython-lib#810]
it would be nice if someone would add the `[v1.22.2](https://github.com/micropython/micropython/tree/v1.22.2)` tag to this repo as well.

I assume it would be to 7cdf70881519c73667efbc4a61a04d9c1a49babb, same as v1.22.0 and v1.22.1.

**Comment by dpgeorge** [comment]
Thanks for the reminder.  Now done.
