### ISSUE TITLE
umqtt.simple check_msg() leaves socket in nonblocking state

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython-lib#84]
This causes failure in a subsequent call to subscribe() as reported [here](https://github.com/micropython/micropython/issues/2268#issuecomment-236377550). The following (tested) fix is one option:
```python
    def check_msg(self):
        self.sock.setblocking(False)
        result = self.wait_msg()
        self.sock.setblocking(True)
        return result
```

**Comment by pfalcon** [comment]
Thanks for diagnosing. And a stupid think on m part of course, fixed as was intended in https://github.com/micropython/micropython-lib/commit/4a8ef9f99c12e6093c3dcaf22e822a035ffb18a8
