### ISSUE TITLE
Deque is not a deque

### ISSUE THREAD

**Issue by Kacarott** [micropython/micropython-lib#847]
A deque, as described in [the docs](https://docs.micropython.org/en/latest/library/collections.html#collections.deque), is:

> Deques (double-ended queues) are a list-like container that support O(1) appends and pops from either side of the deque.

And yet [the implementation](https://github.com/micropython/micropython-lib/blob/master/python-stdlib/collections-deque/collections/deque.py) seems to very clearly be just a list, calling itself a deque? And just like a list it has O(N) appends and pops from the left:

```python
class deque:
    def __init__(self, iterable=None):
        if iterable is None:
            self.q = []
        else:
            self.q = list(iterable)

    def popleft(self):
        return self.q.pop(0)

    ...

    def appendleft(self, a):
        self.q.insert(0, a)
```

**Comment by mattytrentini** [comment]
I've raised #848 to remove that now-unnecessary deque implementation.
