### ISSUE TITLE
Consider ways to efficiently implement support for multiple platforms

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython-lib#9]
There's growing interest to support multiple platforms in micropython-lib besides currently supported POSIX/Linux - MacOSX #7, bare-metal (PyBoard) #8, Windows https://github.com/micropython/micropython/pull/886#issuecomment-60064438. Consider ways how to implement it efficiently.

**Comment by jonnor** [comment]
Most modules are supported now on all MicroPython ports. Those that are Unix specific live in a particular subdirectory.
