### ISSUE TITLE
umqtt.simple: query regarding qos == 1

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython-lib#90]

**Comment by pfalcon** [comment]
I'm not sure why you closed this ticket and especially deleted all content.

Retry happens at the top level, so entire publish sequence will be repeated (which may be an issue for QoS2, but it's cunningly not supported). The only issue then is that PUBLISH will be retried with *new* packet ID, unlike standard says. That can be fixed, but would require few lines => more memory pressure. So, unless given non-speculative evidence that this is a real problem for esp8266 software which affects many people, I'd consider this "known issue".

**Comment by peterhinch** [comment]
> Retry happens at the top level

I eventually figured this out and concluded it was a non-issue; there seems to be no way to delete an issue raised in error. Thanks for the response.
