### ISSUE TITLE
[HELP] How to Login Web Site

### ISSUE THREAD

**Issue by MeantCoder** [micropython/micropython-lib#99]
Hello guys,

I'm making basic notifier

I want login fb/twitter/gmail etc. with nodemcu module( with uPython) but i can't imported mechanize or bs4.
how to login fb/twitter/gmail etc. ? thanks

**Comment by pfalcon** [comment]
This is a bugtracker for micropython-lib project. Unless you have a bug to report, please use other means of communication, e.g. http://forum.micropython.org/
